};
/* Data layer: swap this object for Supabase calls (select / insert / update / delete) in the deployed build. */
const store={load(){try{const d=JSON.parse(localStorage.getItem('vv_cms'));if(d)return d}catch(e){}return JSON.parse(JSON.stringify(SEED))},save(d){try{localStorage.setItem('vv_cms',JSON.stringify(d));return true}catch(e){toast('Storage full — use smaller files');return false}}};
const F=(k,l,t)=>[k,l,t];
const SCH={
projects:{t:'Projects',d:'Portfolio projects shown in the Projects section.',f:[F('title'),F('subtitle'),F('tags','Technologies (comma)'),F('desc','Description','ta'),F('role'),F('status'),F('link','Link URL'),F('img','Image','img')]},
hackathons:{t:'Hackathons',d:'Featured hackathon cards.',f:[F('award','Award / Position'),F('level'),F('title'),F('desc','Description','ta'),F('role'),F('team','Team size'),F('outcome'),F('img','Image','img')]},
achievements:{t:'Achievements',d:'Awards and recognitions.',f:[F('title'),F('org','Organization'),F('date'),F('desc','Description','ta'),F('link','Verification link'),F('img','Image','img')]},
certs:{t:'Certifications',d:'Verified accreditations.',f:[F('org','Organization'),F('title','Certificate title'),F('desc','Description','ta'),F('year','Issue date'),F('cid','Certificate ID'),F('link','Verification URL')]},
education:{t:'Education',d:'Education timeline.',f:[F('inst','Institution'),F('degree'),F('dept','Department'),F('dur','Duration'),F('score','CGPA / %'),F('desc','Description / coursework','ta')]},
experience:{t:'Experience',d:'Engineering experience timeline.',f:[F('org','Organization'),F('role','Position'),F('dur','Duration'),F('desc','Description / responsibilities','ta'),F('tech','Technologies (comma)')]},
gallery:{t:'Gallery',d:'Images shown in the lightbox gallery.',f:[F('cap','Caption'),F('cat','Category'),F('img','Image','img')]},
skills:{t:'Skills',d:'Skill categories. Items: one per line as “Name | detail”.',f:[F('name','Category'),F('tag','Badge'),F('desc','Description','ta'),F('items','Skills (Name | detail per line)','ta'),F('foot','Footer note')]}};
const SING={
home:{t:'Home',d:'Hero content.',f:[F('name1','Name (line 1)'),F('name2','Accent letter'),F('badge'),F('sub','Subtitle'),F('role'),F('desc','Description','ta'),F('tags','Tags (comma)'),F('eda','EDA toolchain (one per line)','ta'),F('photo','Profile image','img'),F('die','Die specimen image','img'),F('cap','Portrait caption')]},
about:{t:'About',d:'Profile panel, biography and principles.',f:[F('name'),F('role'),F('inst','Institution'),F('spec','Specialization'),F('focus','Primary focus'),F('hw','Target hardware'),F('status','Status text'),F('disc','Discipline (header)'),F('ptitle','Philosophy title'),F('bio','Biography (one paragraph per line)','ta'),F('pr','Principles (TITLE | text, one per line)','ta')]},
contact:{t:'Contact',d:'Contact links and call-to-action text.',f:[F('cta1','Heading (white)'),F('cta2','Heading (cyan)'),F('cdesc','Text','ta'),F('email'),F('linkedin','LinkedIn URL'),F('github','GitHub URL'),F('youtube','YouTube URL')]},
resume:{t:'Resume',d:'Upload or replace the resume PDF (keep it small — browser storage limit).',f:[F('fname','File name'),F('desc','Description','ta'),F('file','Resume PDF','pdf')]}};
function toast(m){const t=document.createElement('div');t.className='toast';t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}
function dlg(html,wide){const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="mb ${wide?'wide':''}">${html}</div>`;m.addEventListener('click',e=>{if(e.target==m)m.remove()});document.body.appendChild(m);return m}
const blobUrl=d=>{const b=atob(d.split(',')[1]),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return URL.createObjectURL(new Blob([a],{type:'application/pdf'}))};
const vis=a=>(a||[]).filter(x=>!x.hide);
function obs(){const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');o.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.fade').forEach(x=>o.observe(x))}
const sec=(id,n,lab,title,meta,body)=>`<section class="sec" id="${id}"><div class="w"><div class="sh fade"><div><div class="lab">${n} / ${lab}</div><h2>${title}</h2></div><div class="meta">${meta}</div></div>${body}</div></section>`;
const none='<div class="empty">No entries published yet — manage content from the admin dashboard.</div>';
/* ---------- PUBLIC SITE ---------- */
function pub(){
const D=store.load(),h=D.home,a=D.about,c=D.contact,r=D.resume,cols=['--cy','--pu','--ye','--gr'];
const nav=[['home','Home'],['about','About'],['skills','Skills'],['projects','Projects'],['hackathons','Hackathons'],['achievements','Achievements'],['certificates','Certificates'],['education','Education'],['experience','Experience'],['gallery','Gallery'],['contact','Contact']];
const lnk=u=>u?`href="${E(u)}" target="_blank" rel="noopener"`:'';
$('#app').innerHTML=`<header><div class="w hb"><a class="logo" data-go="home">VV</a><div class="brand">${E(h.name1)} ${E(h.name2)}<small>RTL / VLSI ARCHITECTURE</small></div>
<nav id="nav">${nav.map(n=>`<a data-go="${n[0]}">${n[1]}</a>`).join('')}</nav>
<div class="hr"><a class="btn o" data-go="resume">▤ RESUME.RTL</a><a class="btn p" data-go="contact">CONNECT →</a></div><button class="burger" id="bg" aria-label="Menu">☰</button></div></header>
<section class="hero" id="home"><div class="w hg">
<div class="fade"><div class="chip"><i></i>${E(h.badge)}</div><h1>${E(h.name1)}<br><b>${E(h.name2)}</b></h1><div class="sub mono cy">${E(h.sub)}</div><p class="role">${E(h.role)}</p><p class="mu">${E(h.desc)}</p>
<div class="tags">${csv(h.tags).map(t=>`<span>${E(t)}</span>`).join('')}</div><div class="row"><a class="btn p" data-go="skills">▣ Explore Cores</a><a class="btn" data-go="about">Lab Dossier ⌄</a></div></div>
<div class="pcard fade">${h.photo?`<img src="${h.photo}" alt="${E(h.name1)}" onerror="this.style.display='none'">`:''}<div class="pbar"><span>SYNTHESIS READY</span><span class="cy">${E(h.cap)}</span></div></div>
<div class="fade"><div class="card rc"><h4>▦ Domain Core <span>IEEE 1364</span></h4><div class="kv">Target Discipline: <b>RTL Design</b></div><div class="kv">HDL Syntax: <b class="cy">Verilog / SystemVerilog</b></div><div class="kv">Verification: <b>UVM / Testbench</b></div></div>
<div class="card rc"><h4>&gt;_ EDA Toolchain <span class="cy">ACTIVE</span></h4><ul>${lines(h.eda).map(x=>`<li>${E(x)}</li>`).join('')}</ul></div>
<div class="card rc"><div class="meta">Sub-micron die specimen <span class="cy" style="float:right">LITHOGRAPHY</span></div>${h.die?`<img class="die" src="${h.die}" alt="">`:''}</div></div></div></section>`
+sec('about','01','ENGINEERING DOSSIER','ABOUT ME','DISCIPLINE: '+E(a.disc),`<div class="ab"><div class="card fade"><div class="ico">{ }</div><h3 style="font-size:26px">${E(a.name)}</h3><p class="mono cy" style="font-size:14px;margin:6px 0 20px">${E(a.role)}</p>
${[['Institution',a.inst],['Specialization',a.spec],['Primary Focus',a.focus],['Target Hardware',a.hw]].map(x=>`<div class="kv" style="border-top:1px solid #0d2238;padding-top:10px">${x[0]}:<b>${E(x[1])}</b></div>`).join('')}
<div class="kv" style="border-top:1px solid #0d2238;padding-top:14px;margin-top:20px;font-size:11px"><span><span class="cy">●</span> ${E(a.status)}</span><span>STATUS: OPEN</span></div></div>
<div class="card fade"><h3 style="font-size:22px;margin-bottom:20px"><span class="cy mono">01</span> ${E(a.ptitle)}</h3>${lines(a.bio).map(p=>`<p class="mu" style="margin-bottom:16px;font-size:17px">${E(p)}</p>`).join('')}
<div class="pr">${lines(a.pr).map((p,i)=>{const s=p.split('|');return`<div><b>0${i+1} / ${E((s[0]||'').trim())}</b>${E((s[1]||'').trim())}</div>`}).join('')}</div></div></div>`)
+sec('skills','02','CAPABILITY MATRIX','SKILLS','SILICON TO SYSTEM',`<div class="g3">${vis(D.skills).map((s,i)=>`<div class="card sk fade" style="--ac:var(${cols[i%4]})"><div class="skh"><h3>${E(s.name)}</h3><span class="bdg">${E(s.tag)}</span></div><p class="mu" style="font-size:14px">${E(s.desc)}</p>${lines(s.items).map(l=>{const p=l.split('|');return`<div class="r2 mono"><b>${E((p[0]||'').trim())}</b><span>${E((p[1]||'').trim())}</span></div>`}).join('')}<div class="meta ft">${E(s.foot)}</div></div>`).join('')||none}</div>`)
+sec('projects','03','SYSTEM BUILDS','PROJECTS','HARDWARE & FULL-STACK',`<div class="g2">${vis(D.projects).map((p,i)=>`<div class="card pj fade"><div class="meta">PRJ-0${i+1} · ${E(p.status)}</div>${p.img?`<img src="${p.img}" alt="">`:''}<h3>${E(p.title)}</h3><div class="cy mono" style="font-size:13px">${E(p.subtitle)}</div><p class="mu">${E(p.desc)}</p><div class="tg">${csv(p.tags).map(t=>`<span>${E(t)}</span>`).join('')}</div><div class="meta">ROLE: <span style="color:var(--tx)">${E(p.role)}</span></div>${p.link?`<a class="btn p" ${lnk(p.link)} style="align-self:flex-start">View Project →</a>`:''}</div>`).join('')||none}</div>`)
+sec('hackathons','04','COMPETITIVE ENGINEERING','HACKATHONS','PROTOTYPING HIGH-RELIABILITY HARDWARE UNDER TIME CONSTRAINTS',vis(D.hackathons).map((x,i)=>`<div class="card hk fade"><div><span class="aw">${E(x.award)}</span> <span class="meta" style="margin-left:10px">${E(x.level)}</span><h3>${E(x.title)}</h3><p class="mu">${E(x.desc)}</p><div class="m3"><div><small>ROLE:</small>${E(x.role)}</div><div><small>TEAM SIZE:</small>${E(x.team)}</div><div><small>OUTCOME:</small><b>${E(x.outcome)}</b></div></div><div class="row" style="align-items:center"><a class="btn p" data-lb="hackathons:${i}">Examine Architecture →</a><span class="meta">◎ Verified Accreditation</span></div></div>${x.img?`<div class="fr"><img src="${x.img}" alt=""><div><span>LIVE PROTOTYPE BENCH</span><span class="cy">PITCH: 36 HRS SPRINT</span></div></div>`:''}</div>`).join('')||none)
+sec('achievements','05','RECOGNITION','ACHIEVEMENTS','AWARDS & MILESTONES',`<div class="g2">${vis(D.achievements).map(x=>`<div class="card ach fade"><div class="meta">${E(x.org)}${x.date?' · '+E(x.date):''}</div><h3 style="font-size:22px">${E(x.title)}</h3><p class="mu">${E(x.desc)}</p>${x.img?`<img src="${x.img}" alt="">`:''}${x.link?`<a class="cy mono" ${lnk(x.link)} style="font-size:12px">VERIFY ↗</a>`:''}</div>`).join('')||none}</div>`)
+sec('certificates','06','VERIFIED ACCREDITATIONS','CERTIFICATIONS','OFFICIAL HARDWARE & SOFTWARE QUALIFICATIONS',`<div class="g3">${vis(D.certs).map(x=>`<div class="card cf fade"><div class="t"><span>${E(x.org)}</span><span class="mu">ID: ${E(x.cid)}</span></div><h3>${E(x.title)}</h3><p class="mu" style="font-size:15px">${E(x.desc)}</p><div class="ff"><span>ISSUED: ${E(x.year)}</span>${x.link?`<a class="cy" ${lnk(x.link)}>VERIFY ↗</a>`:'<span>—</span>'}</div></div>`).join('')||none}</div>`)
+sec('education','07','ACADEMIC RECORD','EDUCATION','TIMELINE',vis(D.education).map(x=>`<div class="card ed fade"><div class="meta">${E(x.dur)}${x.score?' · '+E(x.score):''}</div><h3 style="font-size:24px;margin:6px 0">${E(x.inst)}</h3><div class="cy mono" style="font-size:13px">${E(x.degree)} — ${E(x.dept)}</div><p class="mu" style="margin-top:10px">${E(x.desc)}</p></div>`).join('')||none)
+sec('experience','08','FIELD LOG','EXPERIENCE','INDUSTRY & LAB WORK',vis(D.experience).map(x=>`<div class="card ed fade" style="border-left-color:var(--gr)"><div class="meta">${E(x.dur)}</div><h3 style="font-size:22px;margin:6px 0">${E(x.role)} · ${E(x.org)}</h3><p class="mu">${E(x.desc)}</p><div class="tg" style="margin-top:12px">${csv(x.tech).map(t=>`<span>${E(t)}</span>`).join('')}</div></div>`).join('')||none)
+sec('gallery','09','VISUAL LOG','GALLERY','BENCH, EVENTS & HARDWARE',`<div class="gal">${vis(D.gallery).map((g,i)=>`<div class="gi fade" data-lb="gallery:${i}"><img src="${g.img}" alt="${E(g.cap)}"><span>${E(g.cap)}${g.cat?' · '+E(g.cat):''}</span></div>`).join('')||none}</div>`)
+sec('contact','10','OPEN CHANNELS','CONTACT','RESPONSE WINDOW: 24–48 HRS',`<div class="ab" style="grid-template-columns:1.2fr 1fr"><div class="fade"><div class="chip">VLSI • RTL • FPGA • VERIFICATION</div><div class="cta">${E(c.cta1)} <b>${E(c.cta2)}</b></div><p class="mu" style="font-size:18px;margin-bottom:28px">${E(c.cdesc)}</p>
<div class="g2">${[['EMAIL','SEND DISPATCH →',c.email?'mailto:'+c.email:''],['LINKEDIN','CONNECT →',c.linkedin],['GITHUB','CODE REPOS →',c.github],['YOUTUBE','DEMOS →',c.youtube]].map(x=>`<a class="card lk" ${x[2]?lnk(x[2]):'title="Set this link in the admin dashboard"'}>${x[0]}<span>${x[1]}</span></a>`).join('')}</div></div>
<form class="card fm fade" id="cform"><label>Name<input name="n" required></label><label>Email<input name="e" type="email" required></label><label>Subject<input name="s" required></label><label>Message<textarea name="m" rows="5" required></textarea></label><button class="btn p" style="justify-content:center">SEND MESSAGE →</button></form></div>`)
+`<section class="sec" id="resume"><div class="w"><div class="card cv fade"><div class="ico">▤</div><h2>CURRICULUM VITAE</h2><div class="mono cy" style="font-size:13px">${E(r.fname)}</div><p>${E(r.desc)}</p><div class="row"><a class="btn p" id="dl">⭳ DOWNLOAD RESUME</a><a class="btn" id="vw">◉ VIEW IN DOCUMENT VIEWER</a></div></div></div></section>
<footer><div class="w"><span>© ${new Date().getFullYear()} ${E(h.name1)} ${E(h.name2)}. ALL RIGHTS RESERVED. ARCHITECTURE POWERED BY SUPABASE & REACT.</span><a href="#/admin/login"><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="4" y="11" width="16" height="10" rx="2"/><path d="M8 11V7a4 4 0 0 1 8 0v4"/></svg>ADMIN LOGIN</a></div></footer>`;
$('#bg').onclick=()=>$('#nav').classList.toggle('open');
$('#cform').onsubmit=e=>{e.preventDefault();const f=e.target;if(!c.email){toast('Contact email not set yet');return}location.href='mailto:'+c.email+'?subject='+encodeURIComponent(f.s.value)+'&body='+encodeURIComponent(f.m.value+'\n\n— '+f.n.value+' ('+f.e.value+')');toast('Opening your mail client…')};
$('#dl').onclick=()=>{if(!r.file){toast('No resume PDF uploaded yet');return}const a=document.createElement('a');a.href=blobUrl(r.file);a.download=r.fname||'resume.pdf';a.click()};
$('#vw').onclick=()=>{if(!r.file){toast('No resume PDF uploaded yet');return}dlg(`<iframe src="${blobUrl(r.file)}" style="width:100%;height:80vh;border:0;background:#fff"></iframe>`,true)};
obs();window.scrollTo(0,0)}
document.addEventListener('click',e=>{const g=e.target.closest('[data-go]');if(g){e.preventDefault();const n=$('#nav');if(n)n.classList.remove('open');const t=$('#'+g.dataset.go);if(t)t.scrollIntoView({behavior:'smooth'})}
const l=e.target.closest('[data-lb]');if(l){const[k,i]=l.dataset.lb.split(':'),x=store.load()[k][+i];if(x&&x.img)dlg(`<img class="big" src="${x.img}" alt=""><p class="mono mu" style="text-align:center;margin-top:10px;font-size:13px">${E(x.cap||x.title)}</p>`,true)}});
/* ---------- ADMIN ---------- */
const sha=async s=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))].map(b=>b.toString(16).padStart(2,'0')).join('');
const getAuth=()=>{try{return JSON.parse(localStorage.getItem('vv_auth'))}catch(e){return null}};
function loginView(){const first=!getAuth();
$('#app').innerHTML=`<div class="lg"><form class="card" id="lf"><div class="logo" style="width:54px;height:54px">VV</div><div><h2 style="font-size:28px">ADMIN ACCESS</h2><div class="meta" style="margin-top:6px">${first?'FIRST-TIME SETUP — CREATE ADMIN CREDENTIALS':'AUTHORIZED PERSONNEL ONLY'}</div></div>
<label>Email / Username<input id="u" autocomplete="username" required></label><label>Password<div class="pw"><input id="p" type="password" autocomplete="current-password" required><button type="button" id="tp">SHOW</button></div></label><div class="err" id="er"></div>
<button class="btn p" id="lb" style="justify-content:center">${first?'CREATE ACCESS →':'LOGIN →'}</button><a href="#" class="meta" style="text-align:center">← Back to portfolio</a>
<div class="meta" style="font-size:10px;line-height:1.5;text-transform:none">Prototype auth: credentials are stored as a hash in this browser only. The deployed build uses Supabase Auth + RLS.</div></form></div>`;
$('#tp').onclick=()=>{const p=$('#p'),s=p.type=='password';p.type=s?'text':'password';$('#tp').textContent=s?'HIDE':'SHOW'};
$('#lf').onsubmit=async e=>{e.preventDefault();const b=$('#lb'),u=$('#u').value.trim(),p=$('#p').value;b.textContent='AUTHENTICATING…';b.disabled=true;await new Promise(r=>setTimeout(r,500));const cr=getAuth();
try{if(!cr){if(p.length<8){$('#er').textContent='Use at least 8 characters.';b.disabled=false;b.textContent='CREATE ACCESS →';return}localStorage.setItem('vv_auth',JSON.stringify({u,h:await sha(p)}))}else if(cr.u!==u||cr.h!==await sha(p)){$('#er').textContent='Invalid credentials.';b.disabled=false;b.textContent='LOGIN →';return}
sessionStorage.setItem('vv_ok','1');location.hash='#/admin/dashboard'}catch(x){$('#er').textContent='Storage unavailable in this browser.';b.disabled=false}}}
let D,tab='dash';
const fieldsHtml=(spec,rec)=>spec.map(([k,l,t])=>{l=l||k[0].toUpperCase()+k.slice(1);const v=rec[k]||'';
if(t=='ta')return`<label>${l}<textarea name="${k}" rows="4">${E(v)}</textarea></label>`;
if(t=='img'||t=='pdf')return`<label>${l}<input type="file" data-k="${k}" data-t="${t}" accept="${t=='pdf'?'application/pdf':'image/*'}">${t=='img'&&v?`<img src="${v}" style="max-height:80px;margin-top:6px;border-radius:4px">`:v?'<span class="cy">File on record</span>':''}</label>`;
return`<label>${l}<input name="${k}" value="${E(v)}"></label>`}).join('');
function bind(form,spec,rec){form.querySelectorAll('input[type=file]').forEach(i=>i.onchange=()=>{const f=i.files[0];if(!f)return;const k=i.dataset.k;if(i.dataset.t=='img'){const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const s=Math.min(1,900/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=im.width*s;c.height=im.height*s;c.getContext('2d').drawImage(im,0,0,c.width,c.height);rec[k]=c.toDataURL('image/jpeg',.78);toast('Image ready — press Save')};im.src=r.result};r.readAsDataURL(f)}else{const r=new FileReader();r.onload=()=>{rec[k]=r.result;toast('PDF ready — press Save')};r.readAsDataURL(f)}})}
const collect=(form,spec,rec)=>spec.forEach(([k,,t])=>{if(!t||t=='ta')rec[k]=form.elements[k].value});
const commit=()=>{if(store.save(D))toast('Changes saved successfully');return true};
function adm(){if(!sessionStorage.getItem('vv_ok')){location.hash='#/admin/login';return}D=store.load();
const items=[['dash','Dashboard'],['home','Home'],['about','About'],['skills','Skills'],['projects','Projects'],['hackathons','Hackathons'],['achievements','Achievements'],['certs','Certifications'],['education','Education'],['experience','Experience'],['gallery','Gallery'],['contact','Contact'],['resume','Resume'],['settings','Site Settings']];
$('#app').innerHTML=`<div class="ad"><aside class="sb"><h4>PARKFOLIO ADMIN</h4><small>CONTENT MANAGEMENT SYSTEM</small>${items.map(i=>`<button data-t="${i[0]}">${i[1]}</button>`).join('')}<button data-t="out" style="color:#ff6b7a">Logout</button></aside><main class="am" id="mn"></main></div>`;
document.querySelector('.sb').onclick=e=>{const t=e.target.dataset.t;if(!t)return;if(t=='out'){sessionStorage.removeItem('vv_ok');location.hash='';return}tab=t;view()};view()}
function view(){document.querySelectorAll('.sb button').forEach(b=>b.classList.toggle('on',b.dataset.t==tab));const m=$('#mn');
if(tab=='dash'){m.innerHTML=`<h1>Dashboard</h1><p class="mu">Overview of published portfolio content.</p><div class="st">${[['TOTAL PROJECTS',D.projects.length],['TOTAL HACKATHONS',D.hackathons.length],['TOTAL CERTIFICATIONS',D.certs.length],['GALLERY ITEMS',D.gallery.length]].map(x=>`<div class="card"><b>${x[1]}</b><span class="meta">${x[0]}</span></div>`).join('')}</div><p style="margin-top:28px"><a class="btn o" href="#" target="_blank">View public site ↗</a></p>`;return}
if(tab=='settings'){m.innerHTML=`<h1>Site Settings</h1><p class="mu">Reset content or credentials for this prototype.</p><div class="row" style="margin-top:20px"><button class="btn d" id="rc">Reset all content to defaults</button><button class="btn d" id="ra">Reset admin credentials</button></div>`;
$('#rc').onclick=()=>dlg(`<h3>Reset all content?</h3><p class="mu">This restores the default portfolio content.</p><div class="row" style="margin-top:16px"><button class="btn d" id="ok">Confirm</button><button class="btn" id="no">Cancel</button></div>`).querySelector('#ok').onclick=()=>{localStorage.removeItem('vv_cms');document.querySelector('.modal').remove();D=store.load();toast('Content reset');view()};
$('#ra').onclick=()=>{localStorage.removeItem('vv_auth');sessionStorage.removeItem('vv_ok');location.hash='#/admin/login'};
document.addEventListener('click',e=>{if(e.target.id=='no')document.querySelector('.modal')?.remove()},{once:true});return}
if(SING[tab]){const s=SING[tab];m.innerHTML=`<h1>${s.t}</h1><p class="mu" style="margin-bottom:20px">${s.d}</p><form class="card fm" id="sf" style="max-width:820px">${fieldsHtml(s.f,D[tab])}<div class="row"><button class="btn p">Save Changes</button><button type="button" class="btn" id="cn">Cancel</button></div></form>`;
const f=$('#sf');bind(f,s.f,D[tab]);f.onsubmit=e=>{e.preventDefault();collect(f,s.f,D[tab]);commit()};$('#cn').onclick=()=>{D=store.load();view()};return}
const s=SCH[tab],a=D[tab];m.innerHTML=`<div class="tb"><div><h1>${s.t}</h1><p class="mu">${s.d}</p></div><button class="btn p" id="add">+ Add New</button></div>${a.length?`<table><tr><th>#</th><th>TITLE</th><th>STATUS</th><th>ACTIONS</th></tr>${a.map((r,i)=>`<tr><td class="mono">${i+1}</td><td>${E(r[s.f[0][0]]||'(untitled)')}</td><td><button class="btn ${r.hide?'':'o'}" data-a="v" data-i="${i}">${r.hide?'Hidden':'Published'}</button></td><td class="ac"><button class="btn" data-a="u" data-i="${i}">↑</button><button class="btn" data-a="d" data-i="${i}">↓</button><button class="btn o" data-a="e" data-i="${i}">Edit</button><button class="btn d" data-a="x" data-i="${i}">Delete</button></td></tr>`).join('')}</table>`:none}`;
const edit=i=>{const rec=i<0?{}:JSON.parse(JSON.stringify(a[i]));const md=dlg(`<h3>${i<0?'Add':'Edit'} — ${s.t}</h3><form id="ef">${fieldsHtml(s.f,rec)}<div class="row"><button class="btn p">Save Changes</button><button type="button" class="btn" id="cx">Cancel</button></div></form>`);const f=md.querySelector('#ef');bind(f,s.f,rec);md.querySelector('#cx').onclick=()=>md.remove();f.onsubmit=e=>{e.preventDefault();collect(f,s.f,rec);if(i<0)a.push(rec);else a[i]=rec;md.remove();commit();view()}};
$('#add').onclick=()=>edit(-1);
m.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{const i=+b.dataset.i,k=b.dataset.a;
if(k=='e')return edit(i);if(k=='v'){a[i].hide=!a[i].hide}else if(k=='u'&&i>0){[a[i-1],a[i]]=[a[i],a[i-1]]}else if(k=='d'&&i<a.length-1){[a[i+1],a[i]]=[a[i],a[i+1]]}
else if(k=='x'){const md=dlg(`<h3>Delete this entry?</h3><p class="mu">This cannot be undone.</p><div class="row" style="margin-top:16px"><button class="btn d" id="ok">Confirm delete</button><button class="btn" id="no">Cancel</button></div>`);md.querySelector('#no').onclick=()=>md.remove();md.querySelector('#ok').onclick=()=>{a.splice(i,1);md.remove();commit();view()};return}
commit();view()})}
function route(){const h=location.hash;if(h=='#/admin/login')loginView();else if(h.startsWith('#/admin'))adm();else pub()}
addEventListener('hashchange',route);route();
